### ISSUE TITLE
User script breaks Foundation javascript to equalize columns

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/folksonomy_frontend#14]
Originally filed at https://github.com/openfoodfacts/openfoodfacts-server/issues/5279

There is a javascript error that prevents some Foundation functions to work (in particular functions for the "equalizer" that resizes the height of the columns).

To reproduce:

1. https://mq-en.openfoodfacts.dev/cgi/user.pl
2. click on  "This is a producer or brand account. "
3. the columns are not resized and there is an error in the javascript console:

```
user.pl:689 Uncaught TypeError: $(...).foundation is not a function
    at HTMLInputElement.<anonymous> (user.pl:689)
    at HTMLInputElement.dispatch (jquery.js? [sm]:25)
    at HTMLInputElement.v.handle (jquery.js? [sm]:24)
```

**Comment by CharlesNepote** [comment]
I found the issue. This is because I added `// @grant       none` in the header of the script: it makes user script running in the same environment as Open Food Facts scripts, so it loads two versions of jQuery, causing a conflict. 

See:
* https://github.com/greasemonkey/greasemonkey/issues/1614

Solution 1
I can keep `// @grant       none` and delete `// @require     https://code.jquery.com/jquery-2.1.4.min.js`: there will be only one script loaded (the one from Open Food Facts page).
PRO: user script integration in Open Food Facts website should be smoother; lighter solution (one jquery loaded)
CON: there can be conflict between Open Food Facts' javascript and user script code.

Solution 2
I can add `// @grant       GM_log` in the headers: user script will be loaded in an isolated environment, avoiding conflicts.
PRO: complete isolation between user script and Open Food Facts javascript
CON: conflicts may occur when we will integrate user script in Open Food Facts

I'm going to choose solution 1.
